version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/api-bank

  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-bank
    volumes:
      - pgdb:/data/postgres
      
volumes:
  pgdb:
    driver: local